### ISSUE TITLE
Corrupted icons

### ISSUE THREAD

**Issue by phatcher** [plantuml-stdlib/Azure-PlantUML#32] opened 2022-01-05 13:30 UTC
The latest merge corrupted some of the icons, and I don't know enough about svg to diagnose what is going on see https://github.com/plantuml-stdlib/Azure-PlantUML/blob/master/AzureSymbols.md

- AzurePowerBIEmbedded
- AzureServiceEndpoint
- AzureSubnet
- AzureVirtualNetworkPeering

It's probably systemic or down to the original icons but as I said I can't really help much.

**Comment by travisnielsen** [comment] 2022-01-08 19:33
I see a few more:

- AzureDevOpsOrganisation
- AzureServiceBusQueue
- AzureServiceBusTopic
- AzureIPAddressSpace
- AzureAdvancedTools
- AzureContainerSettings
- AzureCORS
- AzureQuota

**Comment by travisnielsen** [comment] 2022-01-08 22:21
After a bit of research, I suspect the issue is due to the complexity of converting SVGs and it will be difficult to find a library that is able to transform these files consistently. I wonder folks would be open to taking an alternative approach. I found one that uses Playwright to screenshot the SVG and write out the image to a PNG file. From what I see, this offers complete fidelity to the original SVG and it should be straightforward to integrate into the current build scripts.

I created a [sample application that uses this technique](https://github.com/travisnielsen/svgconvert) and was able to convert all the problematic icons.
![VNet-Subnets_COLOR](https://user-images.githubusercontent.com/3196834/148661838-ca2a7f21-836c-4715-b08c-9b8cea33ab52.png)
![Power-BI-Embedded_COLOR](https://user-images.githubusercontent.com/3196834/148661847-c08fc860-b9de-42d6-b76f-a9885dbb7d04.png)

**Comment by Potherca** [comment] 2022-01-09 13:41
@travisnielsen Thank you for looking into this!

> it will be difficult to find a library that is able to transform these files consistently

Yeah, I concur. Its one of those things thats been bugging me, but I've not got time to address.

Using Playwright might actually be more desireable than our current approach, as it _could_ also be run from other platforms/language than .NET (i.e. for non-windows developers).

The most important thing is that things work (which the current convertion script does not), so I am all for something that fixes this!

Is it possible that you open an MR with the suggested changes?

**Comment by travisnielsen** [comment] 2022-01-09 17:24
Sounds good! And I agree that standardizing on Playwright could help other projects that use different languages. I'll work through the implementation and will create a PR.

**Comment by travisnielsen** [comment] 2022-01-18 01:50
I'm close to wrapping up my update to the build process: [feature/svgupdate](https://github.com/travisnielsen/Azure-PlantUML/tree/feature/svgconvertupdate)

You can find a sample diagram [here](https://gist.github.com/travisnielsen/8b94e497ef92849ffed167016a8df25d)

A few highlights:
* All icons captured in this issue are now render correctly. SVGs are converted to PNG via Playwright.
* Code has been re-platformed to a .NET6 project. This is mainly becuase Playwright requires a .csproj file but I also wasn't a big fan of the C# script approach (personal opinion).
* Code has been re-factored somewhat. Possibility to add unit tests, if desired.
* Build process now works fully on MacOS, Linux, and (of course) Windows. I see potential for automated builds.
* Removed dependencies on `rsvg` and `inkscape`
* Added a code dependency on [svg-net](https://github.com/svg-net/SVG) but this could be eliminated in the future.
* Updated [build documentation](https://github.com/travisnielsen/Azure-PlantUML/blob/feature/svgconvertupdate/scripts/README.md)
* Externalized config settings (file paths), which addresses #9
* Fixed some older icons in the manual folder that were not rendering well: [Genomics](https://github.com/travisnielsen/Azure-PlantUML/blob/feature/svgconvertupdate/dist/AIMachineLearning/MicrosoftGenomics(m).png), [Stream Analytics](https://github.com/travisnielsen/Azure-PlantUML/blob/feature/svgconvertupdate/dist/Analytics/AzureStreamAnalytics(m).png), and [Blob Storage](https://github.com/travisnielsen/Azure-PlantUML/blob/feature/svgconvertupdate/dist/Storage/AzureBlobStorage(m).png) (which isn't really a thing anymore....but I suppose that's a topic for another day).

It's a larger change than I anticipated, but it should be easier to manage going forward.

If we'd like to move forward with a PR, I can include icons from #34.

**Comment by Potherca** [comment] 2022-01-19 00:00
AWE.SOME. This is just awesome! 🤩 


If this is too much effort, well settle for one big MR, but if at all possible, I'd prefer 3 separate oMRs.
One for the code change, one for the SVG fixes, and one adding missing icons.

To avoid extra rebasing hassles, you can open MRs on consecutive branches, like this:

```                                 
o = Merge Request

 master branch  . . . . . . ---+--------o------o------o----
    1st branch  . . . . . . . . \----A-/      /      /
    2nd branch  . . . . . . . . . . . \----B-/      / 
    3rd branch  . . . . . . . . . . . . . . \----C-/ 
```

Just open each MR pointing the previous branch (so only the first MR points to `master`) and GitHub will neatly fold each MR into the main branch, as long as we merge them in the right order.

Again:Great work @travisnielsen!

**Comment by travisnielsen** [comment] 2022-08-06 14:29
@Potherca - I believe this issue can be closed based on the recent merges.

**Comment by Potherca** [comment] 2022-08-06 16:05
I concur. Closing. Thank you @phatcher for reporting the issue and @travisnielsen for fixing it. 🏅

**Closed by Potherca** 2022-08-06 16:05 UTC
