### ISSUE TITLE
C4 examples return Error Fetching Resource

### ISSUE THREAD

**Issue by hukka** [plantuml-stdlib/Azure-PlantUML#12] opened 2019-10-23 11:54 UTC
The picture links for the C4 examples seem to be broken.

**Comment by Potherca** [comment] 2021-01-29 10:47
This seems to be caused by https://github.com/plantuml-stdlib/C4-PlantUML/issues/23 (as mentioned in #13).

Should be fixed by #22.

**Closed** 2021-03-29 08:47 UTC
